apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-spring-petclinic-new
  namespace: openshift-gitops
spec:
  destination:
    namespace: spring-petclinic-new
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: app
    repoURL: https://github.com/nvzjc/openshift-gitops-getting-started.git
#    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
